function createfigure(X1, YMatrix1, X2, Y1, XData1, YData1, X3, YMatrix2, X4, Y2)
%CREATEFIGURE(X1, YMATRIX1, X2, Y1, XDATA1, YDATA1, X3, YMATRIX2, X4, Y2)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data
%  X2:  vector of x data
%  Y1:  vector of y data
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  X3:  vector of x data
%  YMATRIX2:  matrix of y data
%  X4:  vector of x data
%  Y2:  vector of y data

%  Auto-generated by MATLAB on 20-Oct-2016 20:49:50

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1);
hold(subplot1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',subplot1);
set(plot1(1),'DisplayName','X','Color',[0 0 1]);
set(plot1(2),'DisplayName','Y','Color',[1 0 1]);
set(plot1(3),'DisplayName','Z','Color',[1 0 0]);
set(plot1(4),'DisplayName','Selected','LineWidth',1,'Color',[0 1 0]);

% Create plot
plot(X2,Y1,'Parent',subplot1,'Tag','Signal');

% Create line
line(XData1,YData1,'Parent',subplot1,'Tag','Peak',...
    'MarkerFaceColor',[0 0.447 0.741],...
    'Marker','v',...
    'LineStyle','none',...
    'Color',[0 0.447 0.741]);

% Create xlabel
xlabel('Time (sec)');

% Create ylabel
ylabel('User Acceleration (m/s^2)');

% Create title
title({'Cadence of Bike User Ashu'});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot1,[6.00947049312854 10.0373524656427]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot1,[-1.99052132701422 2.50236966824645]);
box(subplot1,'on');
grid(subplot1,'on');
% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1);
hold(subplot2,'on');

% Create multiple lines using matrix input to plot
plot2 = plot(X3,YMatrix2,'Parent',subplot2);
set(plot2(1),'DisplayName','unfilt');
set(plot2(2),'LineWidth',1);

% Create plot
plot(X4,Y2,'Parent',subplot2,'DisplayName','butter LPF','Marker','x',...
    'LineStyle','none');

% Create xlabel
xlabel('Frequency (RPM)');

% Create ylabel
ylabel('Magnitude');

% Create title
title({'FFT of Weighted Averaged Data'});

%% Uncomment the following line to preserve the X-limits of the axes
% xlim(subplot2,[-5.06014429768838 424.204204934325]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(subplot2,[-0.0796865903249872 0.576237580291127]);
box(subplot2,'on');
% Create legend
legend(subplot2,'show');

